### ISSUE TITLE
[epic] Containerize existing TuneTrees app in Docker (and deploy to Digital Ocean)

### ISSUE THREAD

**Issue by sboagy** [sboagy/tunetrees#42]
Containerize existing TuneTrees app in Docker, and deploy to Digital Ocean.

The goal is to access the TuneTrees application from any web browser/machine, and be able to do a practice session.

This issue only describes the current single user functionality.  
* User management, login, etc., is reserved for another issue.  
* Storage of the database (currently [tunetrees.sqlite3](https://github.com/sboagy/tunetrees/blob/main/tunetrees.sqlite3) will be done in the Docker container's transient storage for the moment.  DB storage will be reserved for another issue.

# Sub tasks
- [x] Create and local-test Dockerfile
- [x] Figure out multi-platform build (may need registry??)
- [x] Figure out deploy to DigitalOcean droplet (deploy archive or use registry?)
- [x] Figure out networking details (public port or do I need at least crude password gate?)
- [ ] Configure `baseURL` via env variables (requires frontend (not browser-client), probably via proxy route (see [next.js API Routes article and refs](https://nextjs.org/docs/pages/building-your-application/routing/api-routes) ).
- [x] SSL Certificates
- [ ] #48

# Decisions
* Build multi-platform image via `docker buildx bake all` and use of a `docker-bake.hcl` file, tag and build `docker.io/sboagy/tunetrees-`{server/frontend}`, i.e. push to `sboagy` `docker.io` image repos.
* Down the line probably good to use DigitalOcean image repos.
* `docker compose up --build` still works clean locally for on-laptop testing.
* Deploy simply by scp `compose.yaml` file to the droplet, and then doing `docker compose up` in a droplet session.
* The deploy can be automated down the line a bit with Ansible (I think).
* Networking works, but the `baseURL` will need to be parameterized to use env variables or some such
* SSL Certificates via [Let's Encrypt](https://letsencrypt.org/)
* HTTPS structure pretty much per [Magenta Qin Next.js+Docker+Ngnix+Certbot artical](https://medium.com/@magenta2127/how-to-upgrade-your-website-to-https-in-3-minutes-a-step-by-step-guide-for-independent-7444016545ab).  (See also [How To Secure a Containerized Node.js Application with Nginx, Let's Encrypt, and Docker Compose](https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose).
* Design Issue: May want to consider the front-end calling back to itself from the browser, and then the frontend calling the backend tunetrees server.
